name: 'My Blog '
favicon: null
layout_spectrum: 0.6620819240342826
typography_spectrum: 0.47055206540971994
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.2083416753448546
  lightness: 0.28775154426693916
  saturation: 0.19422062626108527
  rhythmicContrast: 0.7552022421732545
purpose: []
